matrix:
  include:

    # Multicore OCaml
    - language: c
      sudo: required
      script: bash -ex .travis.sh
      os:
        - linux
      env:
        - LANG=multicore-ocaml
        - KIND=ocaml

    # Eff
    - language: c
      sudo: required
      script: bash -ex .travis.sh
      os:
        - linux
      env:
        - LANG=eff
        - KIND=ocaml

    # Frank
    - language: c
      sudo: required
      script: bash -ex .travis.sh
      os:
        - linux
      env:
        - LANG=frank
        - KIND=haskell

    # Scala Effekt
    - language: scala
      addons:
        apt:
          packages:
            - oracle-java8-installer
      jvm:
        - oraclejdk8
      cache:
        directories:
          - $HOME/.ivy2/cache
          - $HOME/.sbt
      env:
        - LANG=scala-effekt
