matrix:
  include:

    # Multicore OCaml
    - language: c
      sudo: required
      script: bash -ex .travis.sh
      os:
        - linux
      env:
        - KIND=ocaml
        - LANG=multicore-ocaml

    # Eff
    - language: c
      sudo: required
      script: bash -ex .travis.sh
      os:
        - linux
      env:
        - KIND=ocaml
        - LANG=eff

    # Frank
    - language: c
      sudo: required
      script: bash -ex .travis.sh
      os:
        - linux
      env:
        - KIND=haskell
        - LANG=frank

    # Scala Effekt
    - language: scala
      jdk:
      - oraclejdk8
      cache:
        directories:
          - $HOME/.ivy2/cache
          - $HOME/.sbt
      env:
        - LANG=scala-effekt
